### ISSUE TITLE
Pass options to browserify plugin

### ISSUE THREAD

**Issue by heri16** [digitalmaas/serverless-plugin-browserifier#7]
How do we pass options to a browserify plugin?

I have tried both:

```
custom:
  browserify:
    plugin:
      - prepackify:
          compatibility: node-cli
```

```
custom:
  browserify:
    plugin:
      - prepackify --compatibility=node-cli
```

**Comment by nolde** [comment]
Could you try this...
```yaml
custom:
  browserify:
    plugin:     
      - - prepackify
        - compatibility: node-cli
```
... and let me know if it works?

Normally, we have to follow `browserify([files] [, opts])` API format, and options like `plugin` or `transform` are usually arrays that contains either strings with the tool name or arrays with tool name and options.
